### PR TITLE
Added the module configuration file.

### PR DESCRIPTION
**Pull request by clarkeverdel**

### CODE REVIEW

**Comment by manticorp** [comment]
Thanks!

**Comment by clarkeverdel** [comment]
No problem at all!

I have some difficulties to make the sphinx search work on my local installation running MAMP.

Did you use a tutorial for this which explains the exact steps?
I’m stuck at getting the sphinx.conf file to work.

Vriendelijke groet, 
Clarke Verdel

http://www.claver-webdesign.nl http://www.claver-webdesign.nl/

**Comment by manticorp** [comment]
It should work on a MAMP server. I just followed the official docs:

http://sphinxsearch.com/docs/current.html#installation

What problem are you having exactly? You might need to tell sphinx which sphinx.conf file to use - it defaults to the one in the directory where you run sphinx, e.g. if you had sphinx located in /usr/local/sphinx, then you might have searchd in /usr/local/sphinx/bin and your conf file in /usr/local/sphinx/etc, so you would do:

```
$ cd /usr/local/sphinx/etc
$ cp sphinx.conf.dist sphinx.conf
$ vi sphinx.conf // edit your conf file
$ ./../bin/indexer --all
$ ./../bin/searchd
```

but you can tell it to use a specific config file thusly:

```
$ searchd --config /home/myuser/sphinx.conf
```

or, shorthand:

```
$ searchd -c /home/myuser/sphinx.conf
```

Does that help at all?

**Comment by clarkeverdel** [comment]
The problem which my shell returns: ERROR: index 'fulltext': sql_query: Table 'bluud.i8ob_sphinx_catalogsearch_fulltext' doesn't exist (DSN=mysql://root:***@127.0.0.1:8889/bluud).

The same problem I get when I try to reindex the fulltext in Magento.

Do you have any idea what the problem might be?

Vriendelijke groet, 
Clarke Verdel

http://www.claver-webdesign.nl http://www.claver-webdesign.nl/

**Comment by manticorp** [comment]
Ah, yes...that's a good point - you'll need to go into the files and edit a few bits - my bad!

If you have means for doing so, do a global search and replace for 'i8ob_' and substitute for your table prefix, otherwise, I think the affected file is:

```
app\code\community\Manticorp\SphinxSearch\Model\Resource\Fulltext\Engine.php
```

I might try and roll out an update in a mo! Good spot! (I think you're the first person to use this other than me ;))

**Comment by manticorp** [comment]
Okay, I've done this...I think, haven't had time to thoroughly test, but it should get table names automatically now :)

**Pull request merged**
